# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antique_price', models.IntegerField(max_length=100)),
                ('antique_title', models.CharField(max_length=250)),
                ('antique_pic', models.CharField(max_length=1000)),
                ('antique_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.IntegerField(max_length=100)),
                ('item_title', models.CharField(max_length=250)),
                ('item_pic', models.CharField(max_length=1000)),
                ('item_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, null=True)),
                ('price', models.IntegerField(default=0, max_length=100, null=True)),
                ('pic', models.CharField(max_length=1000, null=True)),
                ('contact', models.IntegerField(default=0, max_length=10, null=True)),
                ('fname', models.CharField(max_length=10, null=True)),
                ('lname', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('code', models.IntegerField(default=0, max_length=1000, null=True)),
                ('cno', models.IntegerField(default=0, max_length=1000, null=True)),
                ('cc', models.IntegerField(default=0, max_length=1000, null=True)),
                ('m', models.CharField(max_length=10, null=True)),
                ('y', models.IntegerField(default=0, max_length=1000, null=True)),
                ('user1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_price', models.IntegerField(max_length=100)),
                ('painting_title', models.CharField(max_length=250)),
                ('painting_pic', models.CharField(max_length=1000)),
                ('painting_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='auc_id1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='auc_id2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.Painting'),
        ),
        migrations.AddField(
            model_name='cart',
            name='auc_id3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.Antique'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
