# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='antique_pic',
            field=models.ImageField(max_length=1000, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(max_length=1000, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_pic',
            field=models.ImageField(max_length=1000, upload_to=b''),
        ),
    ]
