# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170311_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.CharField(max_length=1000),
        ),
    ]
