# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170311_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='antique_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='painting',
            name='painting_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
