# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170311_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting_pic',
            field=models.CharField(max_length=1000),
        ),
    ]
