# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170312_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='antique_pic',
            field=models.CharField(max_length=1000),
        ),
    ]
