# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20170312_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='antique_bidprice',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_bidprice',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='painting_bidprice',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
