# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170315_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pic',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
