# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0008_cart_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billid', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
