# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='antique_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 6, 55, 15, 377839, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='item_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 6, 55, 15, 373839, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='painting',
            name='painting_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 6, 55, 15, 373839, tzinfo=utc)),
        ),
    ]
