# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20170322_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='cno',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='m',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='y',
        ),
        migrations.AlterField(
            model_name='antique',
            name='antique_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 15, 44, 24, 80266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 15, 44, 24, 79265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 15, 44, 24, 79265, tzinfo=utc)),
        ),
    ]
