# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 16:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0011_auto_20170322_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='antique',
            name='antique_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='item_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='painting',
            name='painting_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='antique',
            name='antique_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 16, 23, 49, 192668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 16, 23, 49, 191667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 16, 23, 49, 192668, tzinfo=utc)),
        ),
    ]
