# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20170322_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='antique_enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 16, 38, 33, 734909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 16, 38, 33, 733908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 16, 38, 33, 734909, tzinfo=utc)),
        ),
    ]
