# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20170322_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='antique_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 23, 18, 33, 31, 100350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 23, 18, 33, 31, 98348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_enddate',
            field=models.DateField(default=datetime.datetime(2017, 3, 23, 18, 33, 31, 99349, tzinfo=utc)),
        ),
    ]
